version: 2
jobs:
  build:
    docker:
      - image: node:8.7.0
    steps:
      - checkout
      - run: 
          name: Install Dependencies
          command: yarn
      - run: 
          name: Run checks
          command: yarn check-all
